# Generated by Django 6.0.3 on 2026-03-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_design', '0002_userprofile_leetcode_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyproblem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyproblem',
            name='is_punishment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyproblem',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skips_remaining',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skips_reset_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='topic_preferences',
            field=models.JSONField(default=list),
        ),
        migrations.AddConstraint(
            model_name='dailyproblem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_punishment', False)), fields=('user', 'assigned_date'), name='unique_primary_per_user_day'),
        ),
        migrations.AddConstraint(
            model_name='dailyproblem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_punishment', True)), fields=('user', 'assigned_date'), name='unique_punishment_per_user_day'),
        ),
    ]
